version: '3.8'

services:
  backend:
    build: .
    container_name: backend_container
    ports:
      - "${PORT}:${PORT}"  
    env_file:
      - .env               
    depends_on:
      - mongo
    command: npm start     
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo:5
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
